## NumPy - Avanzado

En este notebook vamos a explorar diferentes funciones de esta librería enfocadas al trabajo con elementos **bi-dimensionales** (matrices) y manipulación de arrays.

- Indexing y Slicing en NumPy.
- Atributos de los arrays.
- Funciones de agregación.
- Funciones de ordenamiento.
- Manipulación de arrays.
- Creación de arrays.
- Números Aleatorios en NumPy.

In [1]:
import numpy as np

In [2]:
# Versión de NumPy

print(f"numpy=={np.__version__}")

numpy==2.2.1


### Indexing y Slicing en NumPy

#### Indexing

En Python para hacer _**indexing**_ de una lista de listas debiamos escribir primero la _**fila**_ y de segundo la _**columna**_ asi:
```python
lista[a][b]
```

Usando un _**np.array()**_ podemos usar la siguiente notación:
```python
array[a, b]
```

#### Slicing

En Python para hacer _**slicing**_ de una lista de listas debiamos escribir primero la _**fila**_ y de segundo la _**columna**_ asi:
```python
lista[a1:a2][b1:b2]
```

Usando un _**np.array()**_ podemos usar la siguiente notación:
```python
array[a1:a2, b1:b2]
```

También podemos hacer _**slicing**_ dentro del _**indexing**_ (esta operación retorna un array):

```python
array[[a1, a3], [b2, b4]]
```

**Siempre el primer elemento hace referencia a las filas y el segundo hace referencia a las columnas.**

In [3]:
# matriz de ejemplo

matriz = np.array([[1, 0, 0, 0, 0],
                   [0, 0, 2, 0, 0],
                   [1, 1, 0, 0, 1],
                   [2, 1, 1, 1, 0],
                   [1, 2, 1, 2, 2]])

print(matriz)

[[1 0 0 0 0]
 [0 0 2 0 0]
 [1 1 0 0 1]
 [2 1 1 1 0]
 [1 2 1 2 2]]


In [4]:
# Hacer

matriz[4][1]

np.int64(2)

In [5]:
# Es igual que hacer

matriz[4, 1]

np.int64(2)

In [6]:
# Slicing

matriz[1:4, 1:4]

array([[0, 2, 0],
       [1, 0, 0],
       [1, 1, 1]])

In [7]:
# Indexing + Slicing
# El resultado es un array, no un único elemento 

matriz[[1, 3], [2, 4]]

array([2, 0])

#### Atributos de los arrays

|Atributo      |Descripción                                          |
|--------------|-----------------------------------------------------|
|**.dtype**    |Retorna el tipo de dato de los elementos de un array.|
|**.ndim**     |Retorna el número de dimensiones de un array.        |
|**.size**     |Retorna el total de elementos no nulos de un array.  |
|**.shape**    |Retorna en una tupla las dimensiones de un array.    |
| **.T**       |Retorna la transpuesta de una matriz.                |

In [8]:
# .dtype retorna el tipo de dato de los elementos de un array.
matriz.dtype

dtype('int64')

In [9]:
# .ndim retorna el número de dimensiones de un array.
# Como es una matriz tiene 2 dimensiones (filas y columnas)
matriz.ndim

2

In [10]:
# .size retorna el total de elementos no nulos de un array.

matriz.size

25

In [11]:
# .shape retorna en una tupla las dimensiones de un array.
# Como es una matriz y tiene 2 dimensiones, retorna el total de filas y el total de columnas.

matriz.shape

(5, 5)

In [12]:
# .T retorna la transpuesta de una matriz

matriz.T

array([[1, 0, 1, 2, 1],
       [0, 0, 1, 1, 2],
       [0, 2, 0, 1, 1],
       [0, 0, 0, 1, 2],
       [0, 0, 1, 0, 2]])

### Funciones de Agregación

Las funciones de agregación permiten reseumir los datos de un _**array**_ en un único valor.

|Función         |Descripción                                                                                                |
|----------------|-----------------------------------------------------------------------------------------------------------|
|**np.sum()**    |Retorna la suma de todos los elementos del array.                                                          |
|**np.prod()**   |Retorna el producto de todos los elementos del array.                                                      |
|**np.cumsum()** |Retorna la suma acumulada de todos los elementos del array.                                                |
|**np.cumprod()**|Retorna el producto acumulado de todos los elementos del array.                                            |
|**np.mean()**   |Retorna la media de todos los elementos del array.                                                         |
|**np.median()** |Retorna la mediana de todos los elementos del array.                                                       |
|**np.min()**    |Retorna el mínimo de todos los elementos del array.                                                        |
|**np.max()**    |Retorna la máximo de todos los elementos del array.                                                        |
|**np.std()**    |Retorna la desviación estandar de todos los elementos del array.                                           |
|**np.any()**    |Retorna **True** si al menos uno de los elementos del array es **True**. De lo contrario retorna **False**.|
|**np.all()**    |Retorna **True** si todos todos los elementos del array son **True**. De lo contrario retorna **False**.   |


Si es un **array de dos dimensiones** podemos añadir el parámetro _**axis = 0/1**_. Esto retornará la operación por **columna/fila**. El resultado de esa operación será un array, no un único valor.

In [60]:
# array de ejemplo

array = np.array([1, 3, 2, 5, 4, 6, 8, 7, 9, 1, 8, 10])

print(array)

[ 1  3  2  5  4  6  8  7  9  1  8 10]


In [61]:
# np.sum() retorna la suma de todos los elementos del array.

np.sum(array)

np.int64(64)

In [64]:
matriz

array([[1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [1, 1, 0, 0, 1],
       [2, 1, 1, 1, 0],
       [1, 2, 1, 2, 2]])

In [65]:
# Si es una matriz retorna la suma de todos los elementos

np.sum(matriz)

np.int64(19)

In [66]:
# Si añadimos el parámetro "axis = 0/1" entonces retornará la suma por cada columna/fila 

np.sum(matriz, axis = 0)
# np.sum(matriz, axis = 1)

array([5, 4, 4, 3, 3])

In [67]:
np.sum(matriz, axis = 1)

array([1, 2, 3, 5, 8])

In [17]:
# np.prod() retorna el producto de todos los elementos del array.

np.prod(array)

np.int64(29030400)

In [18]:
# Si es una matriz retorna el producto de todos los elementos

np.prod(matriz)

np.int64(0)

In [19]:
# Si añadimos el parámetro "axis = 0/1" entonces retornará el producto por cada columna/fila 

np.prod(matriz, axis = 0)
# np.prod(matriz, axis = 1)

array([0, 0, 0, 0, 0])

In [68]:
np.prod(matriz, axis = 1)

array([0, 0, 0, 0, 8])

In [20]:
# np.cumsum() retorna la suma acumulada de todos los elementos del array.

np.cumsum(array)

array([ 1,  4,  6, 11, 15, 21, 29, 36, 45, 46, 54, 64])

In [72]:
# Para obtener el array original a partir del array suma cumulativa usamos el np.diff
# Si solo tenemos el acumulado, nos interesa sacar cada valor independiente usando np.diff
np.diff(np.cumsum(array), 0, array[0])

array([ 1,  4,  6, 11, 15, 21, 29, 36, 45, 46, 54, 64])

In [21]:
# np.cumprod() retorna el producto acumulado de todos los elementos del array.

np.cumprod(array)

array([       1,        3,        6,       30,      120,      720,
           5760,    40320,   362880,   362880,  2903040, 29030400])

In [22]:
# np.mean() retorna la media de todos los elementos del array.

np.mean(array)

# np.mean(matriz, axis = 1)

np.float64(5.333333333333333)

In [23]:
# np.median() retorna la mediana de todos los elementos del array.

np.median(array)

np.float64(5.5)

In [24]:
# np.min() retorna el mínimo de todos los elementos del array.

np.min(array)

np.int64(1)

In [25]:
# np.max() retorna la máximo de todos los elementos del array.

np.max(array)

np.int64(10)

In [26]:
# np.std() retorna la desviación estandar de todos los elementos del array.

np.std(array)

np.float64(3.009245014211298)

In [27]:
# np.any() retorna True si al menos uno de los elementos del array es True. De lo contrario retorna False.

np.any(array)

np.True_

In [28]:
# np.all() retorna True si todos todos los elementos del array son True. De lo contrario retorna False.

np.all(array)

np.True_

### Funciones de ordenamiento

|Función         |Descripción                                                                                                     |
|----------------|----------------------------------------------------------------------------------------------------------------|
|**np.sort()**   |Retorna un array ordenado de menor a mayor.                                                                     |
|**np.argsort()**|Retorna los indices de los elementos de un array, representan el array ordenado de menor a mayor.               |
|**np.argmin()** |Retorna el índice del elemento menor de un array. Si ese elemento se repite entonces retorna el de menor índice.|
|**np.argmax()** |Retorna el índice del elemento mayor de un array. Si ese elemento se repite entonces retorna el de menor índice.|

In [29]:
# np.sort() retorna un array ordenado de menor a mayor.

np.sort(array)

array([ 1,  1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [30]:
# Ordena por fila

np.sort(matriz, axis = 1)

array([[0, 0, 0, 0, 1],
       [0, 0, 0, 0, 2],
       [0, 0, 1, 1, 1],
       [0, 1, 1, 1, 2],
       [1, 1, 2, 2, 2]])

In [31]:
# Ordena por columa

np.sort(matriz, axis = 0)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2]])

In [32]:
# np.argmin() retorna el índice del elemento menor de un array. Si ese elemento se repite entonces retorna el de menor índice.

# En este ejemplo retorna 0, porque el índice del elemento más pequeño es 0

np.argmin(array)

np.int64(0)

In [33]:
# np.argmax() retorna el índice del elemento mayor de un array. Si ese elemento se repite entonces retorna el de menor índice.

# En este ejemplo retorna 11, porque el índice del elemento más grande es 11

np.argmax(array)

np.int64(11)

### Manipulación de arrays

Estas **funciones/métodos** se utilizan para modificar, transformar o combinar arrays.

|Función             |Descripción                                                                |
|--------------------|---------------------------------------------------------------------------|
|**np.reshape()**    |Modifica la _forma_ de un array (también es un método).                    |
|**np.ravel()**      |_Aplana_ un array de 2 o más dimensiones a 1 dimensión.                    |
|**.flatten()**      |(**Método**) _Aplana_ un array de 2 o más dimensiones a 1 dimensión.       |
|**np.vstack()**     |Une **verticalmente** una colección de arrays del mismo número de columnas.|
|**np.hstack()**     |Une **horizontalmente** una colección de arrays del mismo número de filas. |
|**np.concatenate()**|Es una generalización de las funciones **np.vstack()** y **np.hstack()**.  |
|**np.transpose()**  |Retorna la transpuesta de una matriz. Es una función.                      |
|**.tolist()**       |(**Método**) Transforma un array a lista.                                  |
|**np.where()**      |Retorna los elementos filtrados de un array.                               |

In [73]:
array

array([ 1,  3,  2,  5,  4,  6,  8,  7,  9,  1,  8, 10])

In [34]:
# np.reshape() modifica la forma de un array

np.reshape(array, newshape = (3, 4))

# En este ejemplo estamos usando la variable "array" que tiene en total 12 elementos
# Para usar reshape la nueva forma del array debe de utilizar todos los elementos, no pueden ser más ni menos
# Por eso (3, 4) es una forma valida, ya que 3*4=12

# Esta es una forma fácil de transformar un array de una dimensión a un array de 2 o más dimensiones

C:\Users\alanj\AppData\Local\Temp\ipykernel_21856\3503389013.py:3: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(array, newshape = (3, 4))


array([[ 1,  3,  2,  5],
       [ 4,  6,  8,  7],
       [ 9,  1,  8, 10]])

In [35]:
# Se puede lograr lo mismo usandolo como método

array.reshape(3, 4)

array([[ 1,  3,  2,  5],
       [ 4,  6,  8,  7],
       [ 9,  1,  8, 10]])

In [36]:
# np.ravel() aplana un array de 2 o más dimensiones a 1 dimensión. Es una función

np.ravel(matriz)

array([1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 1, 2, 1, 1, 1, 0, 1, 2,
       1, 2, 2])

In [37]:
# .flatten() Aplana un array de 2 o más dimensiones a 1 dimensión. Es un método

matriz.flatten()

array([1, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 1, 2, 1, 1, 1, 0, 1, 2,
       1, 2, 2])

In [38]:
# np.vstack() une verticalmente una colección de arrays del mismo número de columnas.

np.vstack((matriz, matriz))

array([[1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [1, 1, 0, 0, 1],
       [2, 1, 1, 1, 0],
       [1, 2, 1, 2, 2],
       [1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [1, 1, 0, 0, 1],
       [2, 1, 1, 1, 0],
       [1, 2, 1, 2, 2]])

In [39]:
# np.hstack() une horizontalmente una colección de arrays del mismo número de filas.

np.hstack((matriz, matriz))

array([[1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 2, 0, 0],
       [1, 1, 0, 0, 1, 1, 1, 0, 0, 1],
       [2, 1, 1, 1, 0, 2, 1, 1, 1, 0],
       [1, 2, 1, 2, 2, 1, 2, 1, 2, 2]])

In [40]:
# np.concatenate() es una generalización de las funciones np.vstack() y np.hstack().
# Para indicar en que sentido se hara la concatenación es através del parámetro "axis = 0/1"

np.concatenate((matriz, matriz), axis = 0)

# np.concatenate((matriz, matriz), axis = 1)

array([[1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [1, 1, 0, 0, 1],
       [2, 1, 1, 1, 0],
       [1, 2, 1, 2, 2],
       [1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [1, 1, 0, 0, 1],
       [2, 1, 1, 1, 0],
       [1, 2, 1, 2, 2]])

In [41]:
# np.transpose() retorna la transpuesta de una matriz. Es una función.

np.transpose(matriz)

array([[1, 0, 1, 2, 1],
       [0, 0, 1, 1, 2],
       [0, 2, 0, 1, 1],
       [0, 0, 0, 1, 2],
       [0, 0, 1, 0, 2]])

In [42]:
# .tolist() transforma un array a lista. Es un método.

matriz.tolist()

[[1, 0, 0, 0, 0],
 [0, 0, 2, 0, 0],
 [1, 1, 0, 0, 1],
 [2, 1, 1, 1, 0],
 [1, 2, 1, 2, 2]]

In [74]:
# np.where() retorna los elementos filtrados de un array.
# En este ejemplo va a retornar los elementos mayor a 7.

np.where(array > 7)

(array([ 6,  8, 10, 11]),)

In [44]:
matriz

array([[1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [1, 1, 0, 0, 1],
       [2, 1, 1, 1, 0],
       [1, 2, 1, 2, 2]])

In [45]:
# En el caso de ser una matriz, retornará 2 arrays
# El primero indica la posición en las filas y el segundo la posición en las columnas

np.where(matriz > 1)

(array([1, 3, 4, 4, 4]), array([2, 0, 1, 3, 4]))

### Creación de arrays

Existen varias funciones para inicializar matrices o arrays:

| Función                | Descripción                                                                       |
|------------------------|-----------------------------------------------------------------------------------|
|**np.empty((n, m))**    | Inicializa una matriz $nxm$ vacia.                                                |
|**np.zeros((n, m))**    | Inicializa una matriz $nxm$ de ceros.                                             |
|**np.ones((n, m))**     | Inicializa una matriz $nxm$ de unos.                                              |
|**np.eye(n)**           | Inicializa la matriz identidad de orden $n$.                                      |
|**np.identity(n)**      | Inicializa la matriz identidad de orden $n$.                                      |
|**np.full(shape, elem)**| Inicializa una matriz con la forma de **shape** usando los elementos de **elem**. |
|**np.linspace(a, b, p)**| Inicializa un array de **p** elementos entre **a** y **b**, todos **x-distantes**.|

In [46]:
# Aunque muestre numeros dentro de la matriz, np.empty() la inicializa vacia
# Estos números que se ven estan en memoria y numpy los usa para mostrar la matriz

empty = np.empty(shape = (5, 5), dtype = "int")

print(empty)

[[      1472540369320                 160                   0
                    0   27303570957139968]
 [4189017755886035579 3419490394216495904 2322206415472651376
  3184080310729661218 3467820298285101088]
 [3184145131399556189 3467820306875035680 2336906602263617580
  3467820302580068699 3196765324752986156]
 [3539877901902048860 2318281922439094316 3556471989104041264
  2318281922439159852 9016872058803465266]
 [7233190455505199148 9041856110933406817 8458716092899139628
  8462091486378289524 9021330316595459182]]


In [47]:
# Inicializa una matriz de 1's.

ones = np.ones(shape = (5, 5), dtype = "int8")

print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [48]:
# Inicializa una matriz de 0's.

zeros = np.zeros(shape = (5, 5), dtype = "int8")

print(zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [49]:
# Matriz identidad

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
# np.full() crea una lista con forma "shape" y la llena con un iterable.

full = np.full(shape = (5, 5), fill_value = range(5))

print(full)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [51]:
# np.linspace(a, b, p) crea un array de "p" elementos entre "a" y "b", todos x-distantes

linspace = np.linspace(start = 1, stop = 12, num = 16)

print(linspace)

[ 1.          1.73333333  2.46666667  3.2         3.93333333  4.66666667
  5.4         6.13333333  6.86666667  7.6         8.33333333  9.06666667
  9.8        10.53333333 11.26666667 12.        ]


### Números aleatorios en NumPy

|Función                             |Descripción                                                                                                                                                  |
|------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------|
|**np.random.random(n)**           | Genera un número aleatorio entre 0 y 1, si damos el parametro **n** genera una lista de **n** elementos aleatorios entre 0 y 1, solo genera vectores.|
|**np.random.randn(shape)**        | Genera un array de forma **shape** con números aleatorios. Estos números siguen una distribución normal.                                                      |
|**no.random.randint(a, b, size)** | Genera un array de tamaño **size** con numeros enteros aleatorios entre **a** y **b**.                                                                        |
|**np.random.choice(obj, size, p)**| Genera un array de tamaño **size** con los elementos de **obj**, se le pueden dar pesos a los elementos usando **p**, retorna elementos repetidos.            |
|**np.random.seed(n)**             | Genera una semilla.                                                                                                                                            |
|**np.random.RandomState(n)**      | Genera una semilla.                                                                                                                                            |

In [52]:
# np.random.random() retorna un número entre 0 y 1
# Se puede utilizar para crear arrays de 1, 2 o n-dimensiones

print(np.random.random())

print("-"*30)

print(np.random.random(size = 5))

print("-"*30)

print(np.random.random(size = (5, 5)))

0.7016115889753561
------------------------------
[0.68964923 0.19261587 0.77299464 0.28577091 0.38071809]
------------------------------
[[0.01197418 0.46843089 0.76633194 0.53994737 0.9598987 ]
 [0.49080733 0.46323625 0.69254168 0.67176851 0.11888879]
 [0.8846915  0.45019464 0.60315302 0.51337424 0.83106546]
 [0.50364499 0.78113218 0.46119494 0.608718   0.98062358]
 [0.5363337  0.08456028 0.13617852 0.85967311 0.32723687]]


In [53]:
# np.random.randn() retorna un número aleatorio de una distribución normal
# La distribución tiene mean = 0 y std = 1

print(np.random.randn())

print("-"*30)

print(np.random.randn(2, 3))

-0.2801192248557522
------------------------------
[[ 0.60687547  0.62727269 -0.62603452]
 [ 0.59901583 -0.02050748  1.14538373]]


In [54]:
# np.random.randint() retorna números enteros
# No incluye el límite superior

print(np.random.randint(0, 10))

print("-"*30)

print(np.random.randint(1, 10, size = (5, 5)))

8
------------------------------
[[4 1 6 4 9]
 [5 8 1 2 9]
 [7 1 3 1 8]
 [5 6 2 4 2]
 [6 7 3 6 8]]


In [55]:
# np.random.choice() retorna un array de elementos aleatorios
# Se puede dar pesos a las probabilidades

print(np.random.choice(a    = ["a", "e", "i", "o", "u"],
                       size = 10,
                       p    = [0.6, 0.1, 0.1, 0.1, 0.1])) 

['e' 'a' 'a' 'a' 'a' 'a' 'o' 'o' 'a' 'u']


In [56]:
# np.seed() indica la aleatoriedad que usará NumPy

# En este ejemplo np.seed() afecta a todos los np.random.randn()

for i in range(5):
    
    np.random.seed(0)
    
    print(np.random.randn())

1.764052345967664
1.764052345967664
1.764052345967664
1.764052345967664
1.764052345967664


In [57]:
# En este ejemplo np.seed() solo se aplica al primer np.random.randn()

np.random.seed(0)

for i in range(5):
    
    print(np.random.randn())

1.764052345967664
0.4001572083672233
0.9787379841057392
2.240893199201458
1.8675579901499675


In [58]:
# np.random.RandomState() genera una semilla al igual que np.seed()
# Se diferencia porque puede ser usado para generar número aleatorios sin modificar la aleatoriedad del resto de funciones 

for i in range(4):
    
    rs = np.random.RandomState(2)
    
    print(rs.rand())
    print(rs.randint(0, 10))
    
    print(np.random.randn()) # No usa np.random.RandomState()
    
    print("-"*30)    

0.43599490214200376
8
-0.977277879876411
------------------------------
0.43599490214200376
8
0.9500884175255894
------------------------------
0.43599490214200376
8
-0.1513572082976979
------------------------------
0.43599490214200376
8
-0.10321885179355784
------------------------------


In [59]:
################################################################################################################################