## Ejercicios - NumPy 1

In [1]:
import numpy as np

In [2]:
# Versión
print(f"numpy=={np.__version__}")

numpy==2.2.1


### Ejercicio 1:
- Crea un vector con 10 elementos pares.

In [8]:
lista = []
for i in range(20):
    if i % 2 == 0:
        lista.append(i)

np.array(lista)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
lista = []
for i in range(2, 22, 2):
    lista.append(i)

np.array(lista)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [17]:
array_pares = np.array([i for i in range(2, 22, 2)])
array_pares

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Ejercicio 2:
- Obten el número de dimensiones y el tamaño del vector anterior.

In [18]:
array_pares.ndim

1

In [20]:
# numero de elementos en total
array_pares.size

10

In [21]:
# numero de elementos en cada dimension
array_pares.shape

(10,)

In [24]:
array_pares.dtype

dtype('int64')

In [25]:
array = np.array([10, 10, 20, 20, 30, 30])
array

In [26]:
array_acumulado = np.cumsum(array)
array_acumulado

array([ 10,  20,  40,  60,  90, 120])

In [27]:
np.diff(array_acumulado)

array([10, 20, 20, 30, 30])

In [30]:
# agregar el primero manualmente ya que no tiene ninguno delante para obtener el diff
original = np.insert(np.diff(array_acumulado), 0, array_acumulado[0])
original

array([10, 10, 20, 20, 30, 30])

### Ejercicio 3:
- Crea una lista con 5 números pares y otra lista con 5 números impares utilizando **list comprehension** y conviertelos en una matriz de (5, 2) dimensiones.

In [34]:
pares = np.array([i for i in range(2, 11, 2)])
pares

array([ 2,  4,  6,  8, 10])

In [36]:
impares = np.array([i for i in range(1, 11, 2)])
impares

array([1, 3, 5, 7, 9])

In [42]:
# concatenate y reshape. Por defecto es axis=0. Como es vector de 1 dimensión, axis 1 da error, no hay dos dimensiones
numbers = np.concatenate((pares, impares))
numbers

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [45]:
matriz_5x2 = numbers.reshape(5, 2)
matriz_5x2


array([[ 2,  4],
       [ 6,  8],
       [10,  1],
       [ 3,  5],
       [ 7,  9]])

In [46]:
matriz_5x2.shape

(5, 2)

In [51]:
# lo aplana de 2 dimensiones a una dimensión:
matriz_5x2.flatten()

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [52]:
np.ravel(matriz_5x2)

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])

In [53]:
# esto interesa si los datos son pareados, y están relacionados,
# Por ejemplo si queremos combinar elemento a elemento de un array city_consumption con road_consumption
np.column_stack((pares, impares))

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9]])

In [55]:
print(pares)
print(np.where(pares > 5))

[ 2  4  6  8 10]
(array([2, 3, 4]),)


In [57]:
indices = np.where(pares > 5) # devuelve los indices de los elementos que cumplen con la condiciones/es
pares[indices] # usamos los indices como filtros

array([ 6,  8, 10])

In [58]:
# en pandas
# filtro = df['price'] > 20
# df[filtro]

### Ejercicio 4:
- Obten el tipo de datos de la matriz anterior.

In [47]:
matriz_5x2.dtype

dtype('int64')

### Ejercicio 5:
- Crea una matriz de ceros de dimensión (4, 4) y remplaza los elementos de la diagonal principal por los números 5.

### Ejercicio 6:
- Utiliza la función _**np.linspace()**_ para crear un vector con 10 elementos entre los números: -5 y 5.

### Ejercicio 7:
- Crea una matriz vacía de tamaño (3, 6) con elementos del tipo flotante.

### Ejercicio 8:
- Utiliza la matriz anterior para llenarla con números primos (investiga en internet una función que genere números primos e implementala).

### Ejercicio 9:
- Reemplaza los números de color azul por un 99 utilizando slicing.

$$\Large
\begin{bmatrix}
 1 &  2 &  \color{Blue}{3} &  4 \\
 5 &  \color{Blue}{6} &  7 &  \color{Blue}{8} \\
 \color{Blue}{9} & 10 & 11 & 12 \\
13 & 14 & \color{Blue}{15} & 16
\end{bmatrix}
$$

### Ejercicio 10:
- Obten la primera y tercera fila de la matriz.

### Ejercico 11:
- Obten la tercera columna de la matriz.

### Ejercicio 12:
- Obtener la segunda y tercera columna de la matriz.

### Ejercicio 13:
- Obten una submatriz con los 4 números del centro.

### Ejercicio 14:
- Aplica la función _**np.flatten()**_ a la matriz anterior para obtener un vector.

### Ejercicio 15:
- Aplica el método _**.reshape()**_ al vector anterior para obtener una matriz de (1, 4) dimensiones.

### Ejercicio 16:
- Crea dos matrices de dimensión (4, 4) con números aleatorios y concatenalas verticalmente.

In [2]:
import numpy as np

A = np.random.randn(4,4)
A

array([[ 0.62696094, -2.45494218, -2.13944379, -0.80868188],
       [-0.745848  , -0.70177172, -1.77027287,  0.73776407],
       [ 0.75664601,  0.32662357,  2.05328361, -1.24379719],
       [ 0.61971784,  1.67836997, -0.20175146,  0.778232  ]])

In [3]:
B = np.random.randn(4,4)
B

array([[ 0.42239629,  1.35389391, -0.27789747, -0.56488527],
       [-0.44571148,  0.60678284, -0.31398611,  1.16734768],
       [ 1.24295934,  0.53135175,  0.16334806,  0.39987241],
       [ 2.75641476, -0.01984423,  0.51304574, -0.2412806 ]])

In [5]:
np.concatenate((A, B), axis=0)

array([[ 0.62696094, -2.45494218, -2.13944379, -0.80868188],
       [-0.745848  , -0.70177172, -1.77027287,  0.73776407],
       [ 0.75664601,  0.32662357,  2.05328361, -1.24379719],
       [ 0.61971784,  1.67836997, -0.20175146,  0.778232  ],
       [ 0.42239629,  1.35389391, -0.27789747, -0.56488527],
       [-0.44571148,  0.60678284, -0.31398611,  1.16734768],
       [ 1.24295934,  0.53135175,  0.16334806,  0.39987241],
       [ 2.75641476, -0.01984423,  0.51304574, -0.2412806 ]])

In [8]:
np.vstack((A, B))

array([[ 0.62696094, -2.45494218, -2.13944379, -0.80868188],
       [-0.745848  , -0.70177172, -1.77027287,  0.73776407],
       [ 0.75664601,  0.32662357,  2.05328361, -1.24379719],
       [ 0.61971784,  1.67836997, -0.20175146,  0.778232  ],
       [ 0.42239629,  1.35389391, -0.27789747, -0.56488527],
       [-0.44571148,  0.60678284, -0.31398611,  1.16734768],
       [ 1.24295934,  0.53135175,  0.16334806,  0.39987241],
       [ 2.75641476, -0.01984423,  0.51304574, -0.2412806 ]])

In [ ]:
################################################################################################################################